<?php
  if(isset($_GET['page']))
  {
    $currentPage = $_GET['page'];
    if($currentPage<1)
      $currentPage = 1;
      else if($currentPage>$this->view->so_trang)
        $currentPage = $this->view->so_trang;
    $prePage = $currentPage-1;
    $nextPage = $currentPage+1;
  }
    else
    {
      $currentPage = 1;
      $prePage = $currentPage-1;
      $nextPage = $currentPage+1;
    }
    $lastPage = $this->view->so_trang;
?>
<div>
	<section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="box-header">

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Danh sách tài khoản </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

              <div class="row">
                              <div class="col-lg-2">
                
                <a href="?controller=admin-user&action=danhsachtaikhoan" type="button" class="btn btn-block btn-default btn-lg" > Danh sách tài khoản </a>

              </div>

              <div class="col-lg-2" style="padding-left: 0px">
                
                <a href="?controller=admin-user&action=danhsachnhomtaikhoan" type="button" class="btn btn-block btn-default btn-lg" > Nhóm tài khoản </a>

              </div>

              <div class="col-lg-2" style="padding-left: 0px">
                
                <a href="?controller=admin-user&action=phanquyen" type="button" class="btn btn-block btn-default btn-lg" > Phân quyền </a>

              </div>

              </div>

                <div class="row" style="padding-top: 20px"> 
                    <div class="col-lg-2"> 

                        <a href="?controller=admin-user&action=themtaikhoan" type="button" class="btn btn-block btn-primary"> Thêm tài khoản </a><br>

                    </div>

                </div>  
              
                
              <!-- <div class="row">
                <div class="col-lg-12"> <h3>Tìm kiếm theo </h3> </div>
              </div>

              <div class="row">
                <form action="" method="post">
                    <div class="col-lg-2">
                      <input type="text" class="form-control" placeholder="Tên đăng nhập">
                    </div>

                    <div class="col-lg-2">
                      <input type="text" class="form-control" placeholder="Họ tên">
                    </div>

                    <div class="col-lg-2">
                      <input type="text" class="form-control" placeholder="Email">
                    </div>

                    <div class="col-lg-2">
                      <input type="text" class="form-control" placeholder="Chức vụ">
                    </div>

                    <div class="col-lg-2">
                      <button type="button" class="btn btn-block btn-info"> Tìm </button>
                    </div>

                </form>
              </div> -->

              <table id="" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th> ID </th>
                    <th> Tên đăng nhập</th>
                    <th> Họ tên </th>
                    <th> Email </th>
                    <th> Chức vụ </th>
                    <th> Sửa </th>
                    <th> Xóa</th>
                </tr>
                </thead>
                <tbody>
                <?php                
                  foreach($this->view->listUser as $list){
                    echo "<tr>
                      <td>$list->id_user</td>
                      <td>$list->ten_dang_nhap</td>
                      <td>$list->ho_ten</td>
                      <td>$list->email</td>
                      <td>$list->cong_viec</td>
                      <td><a href='?controller=admin-user&action=suataikhoan&id_user=$list->id_user'> Sửa </a></td>
                      <td><a href='?controller=admin-user&action=xoataikhoan&id_user=$list->id_user'> Xóa </a></td>
                    </tr>";
                  }
                ?>
                 <!--    
                    <tr>
      <td> 1 </td>
      <td> khanhdaik </td> 
      <td> Nguyễn Trọng Khánh </td>
      <td> khanhdaik134 </td>
      <td> Admin  </td>
      <td><a href="?controller=admin-user&action=suataikhoan"> Sửa </a></td>
      <td> <a href="?controller=admin-user&action=xoataikhoan"> Xóa </a></td>

    </tr>
 -->

                </tbody>
                <tfoot>
                <tr>
                    <th> ID </th>
                    <th> Tên đăng nhập</th>
                    <th> Họ tên </th>
                    <th> Email </th>
                    <th> Chức vụ </th>
                    <th> Sửa </th>
                    <th> Xóa</th>
                </tr>
                </tfoot>
              </table>

              <ul class="pagination pagination-sm no-margin pull-right" style="padding-top: 10px">
                <?php
                echo "<li><a href='?controller=admin-user&action=danhsachtaikhoan&page=1'> Trang đầu </a></li>";
                if($prePage>0){
                echo "<li><a href='?controller=admin-user&action=danhsachtaikhoan&page=$prePage'>«</a></li>";
                  echo "<li><a href='?controller=admin-user&action=danhsachtaikhoan&page=$prePage'>$prePage</a></li>";
                }
                  echo "<li><a href='?controller=admin-user&action=danhsachtaikhoan&page=$currentPage'>$currentPage</a></li>";
                if($nextPage<=$this->view->so_trang){
                  echo "<li><a href='?controller=admin-user&action=danhsachtaikhoan&page=$nextPage'>$nextPage</a></li>";
                echo "<li><a href='?controller=admin-user&action=danhsachtaikhoan&page=$nextPage'>»</a></li>";
                }
                echo "<li><a href='?controller=admin-user&action=danhsachtaikhoan&page=$lastPage'> Trang cuối </a></li>";
                ?>
              </ul>


            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      <!-- /.row -->
    </section>
</div>