<div>
  <section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="box-header">

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Danh sách nhóm tài khoản </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

              <div class="row">
                              <div class="col-lg-2">
                
                <a href="?controller=admin-user&action=danhsachtaikhoan" type="button" class="btn btn-block btn-default btn-lg" > Danh sách tài khoản </a>

              </div>

              <div class="col-lg-2" style="padding-left: 0px">
                
                <a href="?controller=admin-user&action=danhsachnhomtaikhoan" type="button" class="btn btn-block btn-default btn-lg" > Nhóm tài khoản </a>

              </div>

              <div class="col-lg-2" style="padding-left: 0px">
                
                <a href="?controller=admin-user&action=phanquyen" type="button" class="btn btn-block btn-default btn-lg" > Phân quyền </a>

              </div>

              </div>


              <div class="row" style="padding-top: 20px">

				

                <div class="col-lg-2"> 
                  <a href="?controller=admin-user&action=themphanquyen" type="button" class="btn btn-block btn-primary"> Thêm phân quyền </a><br>

                </div>
                <form action="" method="post">
                    


                </form>
               </div>


              <table id="" class="table table-bordered table-striped">
                <thead>
                <tr style="font-weight: bold;">
                    <th> Nhóm tài khoản </th>
                    <th> Chức năng </th>
                    <td> Trạng thái </td>
                    <th> Sửa </th>
                    <th> Xóa </th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach($this->view->listPQ as $list){
                  echo "<tr>
                    <td>$list->ten_nhom</td>
                    <td>$list->ten_chuc_nang</td>
                    <td>$list->trang_thai</td>
                    <td><a href='?controller=admin-user&action=suaphanquyen&id_ntk=$list->id_ntk&id_chuc_nang=$list->id_chuc_nang'> Sửa </a></td>
                    <td><a href='?controller=admin-user&action=xoaphanquyen&id_ntk=$list->id_ntk&id_chuc_nang=$list->id_chuc_nang'> Xóa </a></td>
                  </tr>";
                }
                ?>     

                </tbody>
                <tfoot>
                <tr style="font-weight: bold;">
                    <th> Nhóm tài khoản </th>
                    <th> Chức năng </th>
                    <td> Trạng thái </td>
                    <th> Sửa </th>
                    <th> Xóa </th>
                </tr>
                </tfoot>
              </table>

              <!-- <ul class="pagination pagination-sm no-margin pull-right" style="padding-top: 10px">
                <li><a href="#">«</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">»</a></li>
              </ul> -->


            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      <!-- /.row -->
    </section>
</div>