<?php
  if(isset($_GET['page']))
  {
    $currentPage = $_GET['page'];
    if($currentPage<1)
      $currentPage = 1;
      else if($currentPage>$this->view->so_trang)
        $currentPage = $this->view->so_trang;
    $prePage = $currentPage-1;
    $nextPage = $currentPage+1;
  }
    else
    {
      $currentPage = 1;
      $prePage = $currentPage-1;
      $nextPage = $currentPage+1;
    }
    $lastPage = $this->view->so_trang;
?>
<div>
	<section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="box-header">

          <div class="box">
            <div class="box-header">
              <h3 class="box-title"> Danh sách xe </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

              <div class="row">
              <div class="col-lg-2">
                
                <a href="?controller=admin-user&action=quanlyxe" type="button" class="btn btn-block btn-default btn-lg" > Danh sách xe </a>

              </div>


              </div>

                <div class="row" style="padding-top: 20px"> 
                    <div class="col-lg-2"> 

                        <a href="?controller=admin-user&action=themxe" type="button" class="btn btn-block btn-primary"> Thêm xe </a><br>

                    </div>

                </div>  
              
                
              
              <table id="" class="table table-bordered table-striped">
                <thead>
                <tr style="font-weight: bold;"> 
                  <td> ID </td>
                  <td> Tên xe </td>
                  <td> Màu xe </td>
                  <td> Số ghế </td>
                  <td> Nhà sản xuất </td>
                  <td> Giá cho thuê </td>
                  <td> Vận tốc </td>
                  <td> Đời xe </td>
                  <td> Biển số </td>
                  <td> Loại xe </td>
                  <td> Sửa </td>
                  <td> Xóa </td>
                </tr>
                </thead>


                <tbody>
                <?php
                foreach($this->view->listXe as $list){
                  echo "<tr>
                    <td>$list->id</td>
                    <td>$list->ten_xe</td>
                    <td>$list->mau_xe</td>
                    <td>$list->so_ghe</td>                   
                    <td>$list->ten_nsx</td>
                    <td>$list->gia_thue_moi</td>
                    <td>$list->van_toc</td>
                    <td>$list->doi_xe</td>
                    <td>$list->bien_so</td>
                    <td>$list->ten</td>
                    <td><a href='?controller=admin-user&action=suaxe&id=$list->id'> Sửa </a></td>
                    <td><a href='?controller=admin-user&action=xoaxe&id=$list->id'> Xóa </a></td>
                  </tr>";
                }
                ?> 
                    
                </tbody>
                <tfoot>
                <tr style="font-weight: bold;"> 
                  <td> ID </td>
                  <td> Tên xe </td>
                  <td> Màu xe </td>
                  <td> Số ghế </td>
                  <td> Nhà sản xuất </td>
                  <td> Giá cho thuê </td>
                  <td> Vận tốc </td>
                  <td> Đời xe </td>
                  <td> Biển số </td>
                  <td> Loại xe </td>
                  <td> Sửa </td>
                  <td> Xóa </td>
                </tr>                </tfoot>
              </table>

              <ul class="pagination pagination-sm no-margin pull-right" style="padding-top: 10px">
                <?php
                echo "<li><a href='?controller=admin-user&action=quanlyxe&page=1'> Trang đầu </a></li>";
                if($prePage>0){
                echo "<li><a href='?controller=admin-user&action=quanlyxe&page=$prePage'>«</a></li>";
                  echo "<li><a href='?controller=admin-user&action=quanlyxe&page=$prePage'>$prePage</a></li>";
                }
                  echo "<li><a href='?controller=admin-user&action=quanlyxe&page=$currentPage'>$currentPage</a></li>";
                if($nextPage<=$this->view->so_trang){
                  echo "<li><a href='?controller=admin-user&action=quanlyxe&page=$nextPage'>$nextPage</a></li>";
                echo "<li><a href='?controller=admin-user&action=quanlyxe&page=$nextPage'>»</a></li>";
                }
                echo "<li><a href='?controller=admin-user&action=quanlyxe&page=$lastPage'> Trang cuối </a></li>";
                ?>
              </ul>


            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      <!-- /.row -->
    </section>
</div>