<?php
  if(isset($_GET['page']))
  {
    $currentPage = $_GET['page'];
    if($currentPage<1)
      $currentPage = 1;
      else if($currentPage>$this->view->so_trang)
        $currentPage = $this->view->so_trang;
    $prePage = $currentPage-1;
    $nextPage = $currentPage+1;
  }
    else
    {
      $currentPage = 1;
      $prePage = $currentPage-1;
      $nextPage = $currentPage+1;
    }
    $lastPage = $this->view->so_trang;
?>
<div>
	<section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="box-header">

          <div class="box">
            <div class="box-header">
              <h3 class="box-title"> Danh sách bài viết </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

              <div class="row">
                              <div class="col-lg-2">
                
                <a href="?controller=admin-user&action=quanlybaiviet" type="button" class="btn btn-block btn-default btn-lg" > Danh sách bài viết </a><br>

              </div>


              </div>
                
              <!-- <div class="row">
                <div class="col-lg-12"> <h3>Tìm kiếm theo </h3> </div>
              </div>

              <div class="row">
                <form action="" method="post">
                    <div class="col-lg-1">
                      <input type="text" class="form-control" placeholder="ID">
                    </div>

                    <div class="col-lg-1">
                      <input type="text" class="form-control" placeholder="Tên bài viết">
                    </div>

                    <div class="col-lg-1">
                      <button type="button" class="btn btn-block btn-info"> Tìm </button>
                    </div>

                </form>
              </div> -->

              <table id="" class="table table-bordered table-striped">
                <thead>
                <tr style="font-weight: bold;"> 
                  <td> ID </td>
                  <td> Tên bài viết</td>
                  <td> Tóm tắt </td>
                  <td> Ngày đăng </td>
                  <td> Trạng thái </td>
                  <td> Lượt xem </td>
                  <td> ID người duyệt </td>
                </tr>
                </thead>


                <tbody>
                <?php
                foreach($this->view->listBV as $list){
                  echo "<tr>
                    <td>$list->id</td>
                    <td>$list->ten_bv</td>
                    <td>$list->tom_tat</td>
                    <td>$list->ngay_dang</td>
                    <td>$list->trang_thai</td>
                    <td>$list->luot_xem</td>
                    <td>$list->id_nguoi_kiem_duyet</td>
                    <td><a href='?controller=admin-user&action=suabaiviet&id=$list->id'> Sửa </a></td>
                    <td><a href='?controller=admin-user&action=xoabaiviet&id=$list->id'> Xóa </a></td>
                  </tr>";
                }
                ?>

                </tbody>
                <tfoot>
                <tr style="font-weight: bold;"> 
                  <td> ID </td>
                  <td> Tên bài viết</td>
                  <td> Tóm tắt </td>
                  <td> Ngày đăng </td>
                  <td> Trạng thái </td>
                  <td> Lượt xem </td>
                  <td> ID người duyệt </td>
                </tr>
                </tfoot>
              </table>

              <ul class="pagination pagination-sm no-margin pull-right" style="padding-top: 10px">
                <?php
                echo "<li><a href='?controller=admin-user&action=quanlybaiviet&page=1'> Trang đầu </a></li>";
                if($prePage>0){
                echo "<li><a href='?controller=admin-user&action=quanlybaiviet&page=$prePage'>«</a></li>";
                  echo "<li><a href='?controller=admin-user&action=quanlybaiviet&page=$prePage'>$prePage</a></li>";
                }
                  echo "<li><a href='?controller=admin-user&action=quanlybaiviet&page=$currentPage'>$currentPage</a></li>";
                if($nextPage<=$this->view->so_trang){
                  echo "<li><a href='?controller=admin-user&action=quanlybaiviet&page=$nextPage'>$nextPage</a></li>";
                echo "<li><a href='?controller=admin-user&action=quanlybaiviet&page=$nextPage'>»</a></li>";
                }
                echo "<li><a href='?controller=admin-user&action=quanlybaiviet&page=$lastPage'> Trang cuối </a></li>";
                ?>
              </ul>


            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      <!-- /.row -->
    </section>
</div>