<?php
  if(isset($_GET['page']))
  {
    $currentPage = $_GET['page'];
    if($currentPage<1)
      $currentPage = 1;
      else if($currentPage>$this->view->so_trang)
        $currentPage = $this->view->so_trang;
    $prePage = $currentPage-1;
    $nextPage = $currentPage+1;
  }
    else
    {
      $currentPage = 1;
      $prePage = $currentPage-1;
      $nextPage = $currentPage+1;
    }
    $lastPage = $this->view->so_trang;
?>
<div>
  <section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="box-header">

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Danh sách tỉnh </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">


              <div class="row" style="padding-top: 20px">

				

                <div class="col-lg-2"> 
                  <a href="?controller=admin-user&action=themphuong" type="button" class="btn btn-block btn-primary"> Thêm phường </a><br>

                </div>
                <form action="" method="post">
                    


                </form>
               </div>


              <table id="" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th> ID phường </th>
                    <th> Tên phường </th>
                    <th> Sửa </th>
                    <th> Xóa </th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach($this->view->listPhuong as $list){
                  echo "<tr>
                    <td>$list->id</td>
                    <td>$list->ten_phuong</td>
                    <td><a href='?controller=admin-user&action=suaphuong&id=$list->id&currentPage=$currentPage'> Sửa </a></td>
                    <td><a href='?controller=admin-user&action=xoaphuong&id=$list->id&currentPage=$currentPage'> Xóa </a></td>
                  </tr>";
                }
                ?>
                </tbody>
                <tfoot>
                <tr>
                    <th> ID phường </th>
                    <th> Tên phường </th>
                    <th> Sửa </th>
                    <th> Xóa </th>
                </tr>
                </tfoot>
              </table>

              <ul class="pagination pagination-sm no-margin pull-right" style="padding-top: 10px">
                <?php
                echo "<li><a href='?controller=admin-user&action=quanlyphuong&page=1'> Trang đầu </a></li>";
                if($prePage>0){
                echo "<li><a href='?controller=admin-user&action=quanlyphuong&page=$prePage'>«</a></li>";
                  echo "<li><a href='?controller=admin-user&action=quanlyphuong&page=$prePage'>$prePage</a></li>";
                }
                  echo "<li><a href='?controller=admin-user&action=quanlyphuong&page=$currentPage'>$currentPage</a></li>";
                if($nextPage<=$this->view->so_trang){
                  echo "<li><a href='?controller=admin-user&action=quanlyphuong&page=$nextPage'>$nextPage</a></li>";
                echo "<li><a href='?controller=admin-user&action=quanlyphuong&page=$nextPage'>»</a></li>";
                }
                echo "<li><a href='?controller=admin-user&action=quanlyphuong&page=$lastPage'> Trang cuối </a></li>";
                ?>
              </ul>


            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      <!-- /.row -->
    </section>
</div>