<div>
	<section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="box-header">

          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"> Sửa bài viết</h3>
            </div>
            <?php
              if(isset($this->view->res))
              {

                if(is_numeric($this->view->res)){

                echo "<p style='color: green;'>Sửa bài viết thành công. Đang chuyển về trang danh sách </p>";
                  echo "<meta http-equiv='refresh' content='1;url=?controller=admin-user&action=quanlybaiviet'>";
                }else
                echo "<p style='color: red;'>Lỗi quá trình sửa: {$this->view->res} </p>";

              }
            ?>
            <!-- /.box-header -->
              <form action="" method="post">
                <div class="box-body">
                  <div class="row">

                    <div class="col-lg-12">                     

                      <div class="form-group">
                          <label> Tên bài viết </label>
                          <input type="text" value="<?php echo $this->view->bvDetail['ten_bv']; ?>" class="form-control" name="ten_bv">
                      </div>

                      <div class="form-group">
                          <label> Tóm tắt </label>
                          <input type="text" value="<?php echo $this->view->bvDetail['tom_tat']; ?>" class="form-control" name="tom_tat">
                      </div>



                  </div>

                </div>
                </div>

<div class="box-footer">
  <button type="submit" name="sua_bai_viet" class="btn btn-primary"> Cập nhật </button>

</div>



              </form>



          </div>
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      <!-- /.row -->
    </section>
</div>