<div>
	<section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="box-header">

          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"> Thêm phân quyền </h3>
            </div>
            <?php
              if(isset($this->view->res))
              {

                if(is_numeric($this->view->res)){
                echo "<p style='color: green;'>Thêm phân quyền thành công. Đang chuyển về trang danh sách </p>";
                  echo "<meta http-equiv='refresh' content='1;url=?controller=admin-user&action=phanquyen'>";
                }else
                echo "<p style='color: red;'>Lỗi quá trình thêm mới: {$this->view->res} </p>";

              }
            ?>
            <!-- /.box-header -->
              <form action="" method="post">
                <div class="box-body">
                  <div class="row">
                  <div class="form-group col-lg-2">
                      <label> Nhóm tài khoản </label>
                      <select class="form-control" name="id_ntk">
                        <option value="">--- Chọn nhóm tài khoản ----</option>
                        <?php 
                          foreach($this->view->selectNTK as $list){
                            echo "<option value='{$list->id}'>{$list->ten_nhom}</option>";
                          }
                        ?>
                      </select>
                  </div>

                  <div class="form-group col-lg-2">
                      <label> Chức năng </label>
                      <select class="form-control" name="id_chuc_nang">
                        <option value="">--- Chọn chức năng ----</option>
                        <?php 
                          foreach($this->view->selectCN as $list){
                            echo "<option value='{$list->id}'>{$list->ten_chuc_nang}</option>";
                          }
                        ?>
                      </select>
                  </div>

                  <div class="form-group col-lg-2">
                      <label> Trạng thái </label>
                      <select class="form-control" name="trang_thai">
                        <option> --Trạng thái--</option>
                        <option> 0 </option>
                        <option> 1 </option>
                      </select>
                  </div>

                  </div>

                </div>



<div class="box-footer">
  <button type="submit" name="them_phan_quyen" class="btn btn-primary"> Thêm phân quyền </button>
</div>



              </form>



          </div>
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      <!-- /.row -->
    </section>
</div>