<div>
	<section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="box-header">

          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"> Thêm thông tin xe </h3>
            </div>
            <?php
              if(isset($this->view->res))
              {

                if(is_numeric($this->view->res)){

                echo "<p style='color: green;'>Thêm xe thành công. Đang chuyển về trang danh sách </p>";
                  echo "<meta http-equiv='refresh' content='1;url=?controller=admin-user&action=quanlyxe'>";
                }else
                echo "<p style='color: red;'>Lỗi quá trình thêm mới: {$this->view->res} </p>";

              }
            ?>
            <!-- /.box-header -->
              <form action="" method="post">
                <div class="box-body">
                  <div class="row">

                    <div class="col-lg-5">
                  <div class="form-group">
                      <label> Tên xe </label>
                      <input type="text" class="form-control" name="ten_xe" placeholder="Nhập tên xe">
                  </div>

                  <div class="form-group">
                      <label> Màu xe </label>
                      <input type="text" class="form-control" name="mau_xe" placeholder="Màu xe">
                  </div>

                  <div class="form-group">
                      <label> Số ghế </label>
                      <input type="text" class="form-control" name="so_ghe" placeholder="Số ghế">
                  </div>


                  <div class="form-group">
                      <label> Nhà sản xuất </label>
                      <select class="form-control" name="id_nsx">
                        <option value="">--- Chọn nhà sản xuất ----</option>
                        <?php 
                          foreach($this->view->listNSX as $list){
                            echo "<option value='{$list['id']}'>{$list['ten_nsx']}</option>";
                          }
                        ?>
                      </select>
                  </div>


                  <div class="form-group">
                      <label> Giá cho thuê </label>
                      <input type="text" class="form-control" name="gia_thue_moi" placeholder="Giá cho thuê">
                  </div>

                  
                    </div>

     

                  <div class="col-lg-5">
                  <div class="form-group">
                      <label>Vận tốc</label>
                      <input type="text" class="form-control" name="van_toc" placeholder="Nhập vận tốc">
                  </div>

                  <div class="form-group">
                      <label>Đời xe</label>
                      <input type="text" class="form-control" name="doi_xe" placeholder="Nhập đời xe">
                  </div>

                  <div class="form-group">
                      <label>Biển số</label>
                      <input type="text" class="form-control" name="bien_so" placeholder="Nhập biển số">
                  </div>

                  <div class="form-group">
                      <label> Loại xe </label>
                      <select class="form-control" name="loai_xe">
                        <option value="">--- Chọn loại xe ----</option>
                        <?php 
                          foreach($this->view->listTheLoaiXe as $list){
                            echo "<option value='{$list['id']}'>{$list['ten']}</option>";
                          }
                        ?>
                      </select>
                  </div>

                  <div class="form-group">
                      <label>ID công ty</label>
                      <input type="text" class="form-control" name="id_cong_ty" placeholder="Nhập ID công ty">
                  </div>
                </div>
                </div>

<div class="box-footer">
  <button type="submit" name="them_xe" class="btn btn-primary"> Thêm xe </button>
  <button type="reset" name="reset" class="btn btn-primary"> Làm lại </button>

</div>



              </form>



          </div>
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      <!-- /.row -->
    </section>
</div>