<div>
	<section class="content">
      <div class="row">
        <div class="col-xs-12">
            <div class="box-header">

          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title"> Thêm công ty </h3>
            </div>
            <?php
              if(isset($this->view->res))
              {

                if(is_numeric($this->view->res)){

                echo "<p style='color: green;'>Thêm công ty thành công. Đang chuyển về trang danh sách </p>";
                  echo "<meta http-equiv='refresh' content='1;url=?controller=admin-user&action=quanlycongty'>";
                }else
                echo "<p style='color: red;'>Lỗi quá trình thêm mới: {$this->view->res} </p>";

              }
            ?>
            <!-- /.box-header -->
              <form action="" method="post">
                <div class="box-body">
                  <div class="row">

                    <div class="col-lg-5">
                  <div class="form-group">
                      <label> Tên công ty </label>
                      <input type="text" class="form-control" name="ten_cong_ty" placeholder="Nhập tên công ty">
                  </div>

                  <div class="form-group">
                      <label> Tên đại diện </label>
                      <input type="text" class="form-control" name="ten_dai_dien" placeholder="Nhập tên đại diện">
                  </div>

                  <div class="form-group">
                      <label> SĐT người đại diện </label>
                      <input type="text" class="form-control" name="sdt_nguoi_dai_dien" placeholder="Nhập SĐT người đại diện">
                  </div>


                  <div class="form-group">
                      <label> SĐT công ty </label>
                      <input type="text" class="form-control" name="sdt_cong_ty" placeholder="Nhập SĐT công ty ">
                  </div>


                  <div class="form-group">
                      <label> ID tài khoản đại diện </label>
                      <input type="text" class="form-control" name="id_tai_khoan" placeholder="ID tài khoản đại diện">
                  </div>

                  
                    </div>


                    <div class="col-lg-5">
                  <div class="form-group">
                      <label> Email </label>
                      <input type="text" class="form-control" name="email" placeholder="Nhập email">
                  </div>

                  <div class="form-group">
                      <label> Phường </label> <!-- Đoạn này sẽ dùng PHP chèn option vào -->
                      <select class="form-control" name="id_phuong">
                        <option value="">--- Chọn phường ----</option>
                        <?php 
                          foreach($this->view->listPhuong as $list){
                            echo "<option value='{$list->id}'>{$list->ten_phuong}</option>";
                          }
                        ?>
                      </select>
                  </div>

                  <div class="form-group">
                      <label> Quận </label> <!-- Đoạn này sẽ dùng PHP chèn option vào -->
                      <select class="form-control" name="id_quan">
                        <option value="">--- Chọn quận ----</option>
                        <?php 
                          foreach($this->view->listQuan as $list){
                            echo "<option value='{$list->id}'>{$list->ten_quan}</option>";
                          }
                        ?>
                      </select>
                  </div>


                  <div class="form-group">
                      <label> Tỉnh </label> <!-- Đoạn này sẽ dùng PHP chèn option vào -->
                      <!-- <select class="form-control" name="id_tinh">
                        <option> Trúc Bạch </option>
                        <option> Phúc Xá </option>
                        <option> Nghĩa Dũng </option>
                      </select> -->
                      <select class="form-control" name="id_tinh">
                        <option value="">--- Chọn tỉnh ----</option>
                        <?php 
                          foreach($this->view->listTinh as $list){
                            echo "<option value='{$list->id}'>{$list->ten_tinh}</option>";
                          }
                        ?>   
                      </select>
                  </div>

                </div>
                </div>

<div class="box-footer">
  <button type="submit" name="them_cong_ty" class="btn btn-primary"> Tạo công ty </button>
  <button type="reset" name="reset" class="btn btn-primary"> Làm lại </button>

</div>



              </form>



          </div>
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      <!-- /.row -->
    </section>
</div>