<?php 
?>




<div class="container" style="margin-top: 100px;margin-bottom: 100px">
	<form action="" method="post" enctype="multipart/form-data">
		<div class="row">
			<div class="col-md-12">
				<input type="text" name="" placeholder="Tên bài viết" style="width: 100%;margin-bottom: 20px">
			</div>
			<div class="col-md-12">
				<input type="text" name="" placeholder="Tóm tắt" style="width: 100%;margin-bottom: 20px">
			</div>
			<div class="col-md-12">
				<input type="file" name="" placeholder="Ảnh đại diện" style="width: 100%;margin-bottom: 20px">
			</div>
			<div class="col-md-12">
				
					<textarea name="text" id="editor1" rows="50" cols="180">Hello</textarea>
					<div style="height: 50px"></div>
					<p style="text-align:center;"><input type="submit" name="" value="Thêm mới"></p>
				
			</div>

		</div>	
	</form>	
</div>