<?php ?>










<div class="container" style="margin-top: 100px;margin-bottom: 100px">
	<button type = 'button' style = 'padding: 15px;background: white;border:1px solid white;cursor: pointer;width: 100%;' ><a href = '?action=addnews' style = 'color:violet;font-size: 20px;border: 2px solid violet;padding: 15px;text-decoration: none' ><i class="fa fa-plus-square-o" aria-hidden="true"></i>Tạo mới bài viết</a ></button >
	<div style="height: 30px"></div>
	<div class="row">
    <?php
        if (isset($this->view->LoadList) && !empty($this->view->LoadList)){
            foreach ($this->view->LoadList as $row){

                $link_anh = $row['hinh_anh'];
                $edit = "?action=edit-bai-viet&id-bv={$row['id']}";
                $delete = "?action=delete-bai-viet&id-bv={$row['id']}";
                $date = date_create($row['ngay_dang']);
                $newdt = date_format($date,"d/m/Y");


                echo "<div class='col-md-12'>
                    <div class='baiviet' style='margin-bottom: 50px'>
                        
                        <div class='row' style='border: 1px solid #ccc'>
                            <div class='col-md-4'>
                                <div style='padding: 10px;'>
                                    <img src='$link_anh' class='img-fluid' style='max-height: 180px'>
                                </div>
                            </div>
                            <div class='col-md-8'>
                                <div style='min-height: 160px;'>
                                    <h2>{$row['ten_bv']}</h2>
                                    <i class='fa fa-eye' aria-hidden='true'>{$row['luot_xem']} </i>
                                    <i class='fa fa-user-o' aria-hidden='true'> {$row['ho_ten']}</i>
                                    <i class='fa fa-calendar' aria-hidden='true'> $newdt</i><br>
                                    <div class='row'>
                                        <div class='col-md-6'>
                                            <button type = 'button' style = 'padding: 15px;background: white;border:1px solid white;cursor: pointer;width: 100%' ><a href = '$edit' style = 'color: #08c869;font-size: 20px' ><i class='fa fa-pencil-square-o' aria-hidden = 'true' ></i ></a ></button >
                                        </div>
                                        <div class='col-md-6'>
                                            <button type = 'button' style = 'padding: 15px;background: white;border:1px solid white;cursor: pointer;width: 100%' ><a href = '$delete' style = 'color: red;font-size: 20px' ><i class='fa fa-trash' aria-hidden = 'true' ></i ></a ></button >
                                        </div>
                                    </div>
                                </div>
                                <h2 class='flip'><i class='fa fa-angle-double-down' aria-hidden='true'></i>Nội dung<h2>
                                <div class='panel'>
                                    <p style='font-size: 15px'>{$row['noi_dung']}</p>
                                </div>
                                                    
                            </div>	
                        </div>		
        
        
                    </div>	
        
                
                </div>
                ";
            }}


?>










	</div>















</div>



