








<div class="container" style="margin-bottom: 100px;margin-top: 100px">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover table-dark" id="">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Ngày giờ bình luận</th>
                        <th scope="col">Nội dung</th>
                        <th scope="col">Tên xe</th>
                        <th scope="col">Người bình luận</th>
                        <th scope="col">Xóa</th>
                    </tr>
                </thead>
                <tbody>
                <?php
                if (isset($this->view->LoadListOrder) && !empty($this->view->LoadListOrder)){
                    foreach ($this->view->LoadListOrder as $row){
                        $noi_dung = substr($row['noi_dung'],0,50);
                        $detail = "?action=detail-order&id-order={$row['id']}";
                        $delete = "?action=delete-order&id-order={$row['id']}";
                        if ($row['trang_thai']==0)
                            $trang_thai = 'Chưa xác nhận';
                        else
                            $trang_thai = 'Đã xác nhận';

                        $date = date_create($row['ngay_gui']);
                        $new_date = date_format($date,"d/m/Y");

                        echo "<tr>
                            
                            <th scope='row'><a href='$detail'>{$row['id']}</a></th>
                            <td>$new_date</td>
                            <td>$noi_dung</td>
                            <td>$trang_thai</td>

                            <td>{$row['ten_xe']}</td>
                            <td>{$row['ho_ten']}</td>
                            <td><a href='$delete' class='delete-hover'><i class=\"fa fa-trash\" aria-hidden=\"true\"></i></a></td>
                            
                        </tr>";
                    }}
                ?>


                </tbody>
            </table>
    
        </div>   
    </div>





</div>