<?php
?>







<div class="container" style="margin-bottom: 100px;margin-top: 100px">
    <div class="row">
        <div class="col-md-3">


        </div>
        <div class="col-md-6" style="border: 2px solid #ccc;">
            <h3 style="text-align: center;padding: 20px">Thong bao</h3>
            <?php

                if (isset($this->view->thongbao))
                {

                    echo "<p style='color: green;text-align: center;padding: 30px'><i class=\"fas fa-check-circle\" style='color: green;text-align: center;font-size: 200px'></i></p>";
                    echo "<p style='padding: 10px'>";
                    print_r($this->view->thongbao);
                    echo "</p>";


                }
                else{


                    echo "<p style='color: red;text-align: center;padding: 30px'><i class=\"fas fa-exclamation-circle\" style='color: red;text-align: center;font-size: 200px'></i></p>";
                    echo "<p style='padding: 10px'>";
                    print_r($this->view->err);
                    echo "</p>";








                }









                ?>



        </div>
        <div class="col-md-3">


        </div>


















    </div>














</div>








