<?php
?>














<div class="container" style="margin-bottom: 100px;margin-top: 100px">
    <h2 style="text-align: center">Hồ sơ</h2><br>
    <form action="" method="post" enctype="multipart/form-data">
    <div class="row" style="margin-bottom: 50px">
        <div class="col-md-6">
            <label>Tên công ty</label>
            <input type="text" name="ten_ct" placeholder="Ten cong ty" class="form-control" value="<?php echo $this->view->LoadOne['ten_cong_ty']?>">
        </div>
        <div class="col-md-6">
            <label>Số điện thoại công ty</label>
            <input type="text" name="sdt_ct" placeholder="So dien thoai cong ty" class="form-control" value="<?php echo $this->view->LoadOne['sdt_cong_ty']?>">
        </div>

    </div>
    <div class="row" style="margin-bottom: 50px">
        <div class="col-md-6">
            <label>Tên người đại diện</label>
            <input type="text" name="dai_dien" placeholder="Ten nguoi dai dien" class="form-control" value="<?php echo $this->view->LoadOne['ten_dai_dien']?>">
        </div>
        <div class="col-md-6">
            <label>Số điện thoại người đại diện</label>
            <input type="text" name="sdt_dai_dien" placeholder="So dien thoai nguoi dai dien" class="form-control" value="<?php echo $this->view->LoadOne['sdt_nguoi_dai_dien']?>">
        </div>

    </div>
    <div class="row" style="margin-bottom: 50px">
        <div class="col-md-6">
            <label>Email công ty</label>
            <input type="email" name="email" placeholder="Email" class="form-control" value="<?php echo $this->view->LoadOne['email']?>">
        </div>
        <div class="col-md-6">
            <label>Logo</label>
            <input type="file" name="f_upload" placeholder="anh" class="form-control">
        </div>

    </div>
    <div class="row" style="margin-bottom: 50px">
            <div class="col-md-12">
                <label>Đôi nét về công ty</label>
                <textarea class="form-control" rows="7" name="gioi_thieu"><?php echo $this->view->LoadOne['gioi_thieu']?></textarea>
            </div>

    </div>
    <p class="detail"><button type="submit" style="padding: 15px;background: white;border:1px solid black;cursor: pointer"><i class="fas fa-edit">Thay đổi</i></button> </p>
    </form>
    <p class="detail"><button type="button" style="padding: 15px;background: white;border:1px solid black;cursor: pointer"><a href="?action=profile"><i class="fa fa-backward" aria-hidden="true"> Quay về trang cài đặt</i></a> </button> </p>














</div>



















