<div class="container-fluid" style="position: relative;">
	<div class="image" style="background-image: url('public/assets/css/img/background10.png');">
		<div class="image-background">
			<div class="content-gioithieu">
				<h2>GOGO</h2>
				<h5>Dịch vụ cho thuê xe tự lái hàng đầu Việt Nam</h5>
				<div class="separator line-separator">♦</div>
				<h5>Trang chủ/Giới thiệu</h5>
			</div>
		</div>


	</div>
</div>
<div class="container-fluid">
	<div class="container">
		<div class="our-service">
			<h2>Hệ thống của chúng tôi</h2>
			<div class="separator separator-danger">✻</div>
			<p>We promise you a new look and more importantly, a new attitude. We build that by getting to know you, your needs and creating the best looking clothes.</p>
		</div>
		<div class="row" style="margin-top: 40px;margin-bottom: 70px">
                <div class="col-md-4">
                    <div class="info-icon">
                        <div class="icon text-danger">
                            <i class="pe-7s-airplay"></i>
                        </div>
                        <h3>Hệ thống</h3>
                        <p class="description">Hệ thống website thân thiện với người dùng, giúp người dùng có thể chọn được mẫu xe theo nhu cầu của mình</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="info-icon">
                        <div class="icon text-danger">
                            <i class="pe-7s-note2"></i>
                        </div>
                        <h3>Nội dung</h3>
                        <p class="description">Giao diện thiết kế đẹp mắt, nội dung dễ hiểu, hi vọng sẽ đáp ứng được nhu cầu người sử dụng</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="info-icon">
                        <div class="icon text-danger">
                            <i class="pe-7s-car"></i>
                        </div>
                        <h3>Ô tô</h3>
                        <p class="description">Đa dạng,phong phú,đủ những gì mà bạn có thể nghĩ ra</p>
                    </div>
                </div>
        </div>
	</div>
</div>
<div class="container-fluid" style="position: relative;">
	<div class="image2" style="background-image: url('public/assets/css/img/background11.jpeg');">
		<div class="image-background">
			<div class="content-gioithieu2">
				<h2>Chúng tôi là ai?</h2>
				<div class="separator line-separator">♦</div>
				<div class="chu-thich"><p>Chúng tôi là nhóm học sinh đến từ ITPLUS, nhận thấy vấn đề thiết thực về việc đi lại trong đời sống hiện nay, chúng tôi đã quyết định xây dựng hệ thống website cho thuê xe tập trung</p></div>
				<div class="container">
					<div class="row" style="width: 85%;margin: auto;">
						<div class="col-md-4">
							<div class="box-about">
								<div class="avatar2 avatar-danger">
	                                <img alt="..." class="img-circle" src="public/assets/img/avatar1.jpg"/>
	                            </div>
	                            <div class="infor-people">
	                            	<h4>Đặng Thái Sơn</h4>
	                            	<h5>Giảng viên</h5>
	                            	<p>Đừng so sánh mình với bất cứ ai trong thế giới này. Nếu bạn làm như vậy có nghĩa bạn đang sỉ nhục chính bản thân mình</p>
	                            </div>

							</div>
						</div>
						<div class="col-md-4">
							<div class="box-about">
								<div class="avatar2 avatar-danger">
	                                <img alt="..." class="img-circle" src="public/assets/img/avatar2.jpg"/>
	                            </div>
	                            <div class="infor-people">
	                            	<h4>Nguyễn Trọng Khánh</h4>
	                            	<h5>Trưởng nhóm</h5>
	                            	<p>Đừng so sánh mình với bất cứ ai trong thế giới này. Nếu bạn làm như vậy có nghĩa bạn đang sỉ nhục chính bản thân mình</p>
	                            </div>

							</div>
						</div>
						<div class="col-md-4">
							<div class="box-about">
								<div class="avatar2 avatar-danger">
	                                <img alt="..." class="img-circle" src="public/assets/img/avatar3.jpg"/>
	                            </div>
	                            <div class="infor-people">
	                            	<h4>Nguyễn Quốc Nam</h4>
	                            	<h5>Coder</h5>
	                            	<p>Đừng so sánh mình với bất cứ ai trong thế giới này. Nếu bạn làm như vậy có nghĩa bạn đang sỉ nhục chính bản thân mình</p>
	                            </div>

							</div>
						</div>

						<div class="col-md-4">
							<div class="box-about">
								<div class="avatar2 avatar-danger">
	                                <img alt="..." class="img-circle" src="public/assets/img/avatar4.jpg"/>
	                            </div>
	                            <div class="infor-people">
	                            	<h4>Trần Duy Phương</h4>
	                            	<h5>Designer</h5>
	                            	<p>Đừng so sánh mình với bất cứ ai trong thế giới này. Nếu bạn làm như vậy có nghĩa bạn đang sỉ nhục chính bản thân mình</p>
	                            </div>

							</div>
						</div>
						<div class="col-md-4">
							<div class="box-about">
								<div class="avatar2 avatar-danger">
	                                <img alt="..." class="img-circle" src="public/assets/img/avatar5.jpg"/>
	                            </div>
	                            <div class="infor-people">
	                            	<h4>Quân</h4>
	                            	<h5>Coder</h5>
	                            	<p>Đừng so sánh mình với bất cứ ai trong thế giới này. Nếu bạn làm như vậy có nghĩa bạn đang sỉ nhục chính bản thân mình</p>
	                            </div>

							</div>
						</div>
						<div class="col-md-4">
							<div class="box-about">
								<div class="avatar2 avatar-danger">
	                                <img alt="..." class="img-circle" src="public/assets/img/avatar6.jpg"/>
	                            </div>
	                            <div class="infor-people">
	                            	<h4>Phan Hoàng Bin</h4>
	                            	<h5>Coder</h5>
	                            	<p>Đừng so sánh mình với bất cứ ai trong thế giới này. Nếu bạn làm như vậy có nghĩa bạn đang sỉ nhục chính bản thân mình</p>
	                            </div>

							</div>
						</div>

						
					</div>
				</div>
			</div>
			
		</div>

		
	</div>
</div>
<div class="container-fluid">
	<div class="container">
		<div class="our-service">
			<h2>Một vài video về xe của chúng tôi</h2>
			<div class="separator separator-danger">✻</div>
			<p>We promise you a new look and more importantly, a new attitude. We build that by getting to know you, your needs and creating the best looking clothes.</p>
		</div>
		
             <!-- Grid row -->
				<div class="row" style="margin-top: 40px;margin-bottom: 70px">

				    <!-- Grid column -->
				    <div class="col-lg-4 col-md-12 mb-4">

				        <!--Modal: Name-->
				        <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				            <div class="modal-dialog modal-lg" role="document">

				                <!--Content-->
				                <div class="modal-content">

				                    <!--Body-->
				                    <div class="modal-body mb-0 p-0">


				                        <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
				                            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/0tJ_79J7Pj4" allowfullscreen></iframe>
				                        </div>

				                    </div>

				                    <!--Footer-->
				                    <div class="row modal-footer justify-content-center">
				                        <span class="col-md-2 col-12 mr-4">Theo dõi qua!</span>
				                        <a type="button" class="col-md-2 col-3 btn-floating btn-sm btn-fb"><i class="fa fa-facebook"></i></a>
				                        <!--Twitter-->
				                        <a type="button" class="col-md-2 col-3 btn-floating btn-sm btn-tw"><i class="fa fa-twitter"></i></a>
				                        <!--Google +-->
				                        <a type="button" class="col-md-2 col-3 btn-floating btn-sm btn-gplus"><i class="fa fa-google-plus"></i></a>
				                        <!--Linkedin-->
				                        <a type="button" class="col-md-2 col-3 btn-floating btn-sm btn-ins"><i class="fa fa-linkedin"></i></a>

				                        <button type="button" class="col-md-2 col-12 btn btn-outline-primary btn-rounded btn-md ml-4" data-dismiss="modal">Close</button>

				                    </div>

				                </div>
				                <!--/.Content-->

				            </div>
				        </div>
				        <!--Modal: Name-->

				        <a><img class="img-fluid z-depth-1" src="public/assets/img/video-screen1.png" alt="video" data-toggle="modal" data-target="#modal1"></a>

				    </div>
				    <!-- Grid column -->

				    <!-- Grid column -->
				    <div class="col-lg-4 col-md-6 mb-4">

				        <!--Modal: Name-->
				        <div class="modal fade" id="modal6" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				            <div class="modal-dialog modal-lg" role="document">

				                <!--Content-->
				                <div class="modal-content">

				                    <!--Body-->
				                    <div class="modal-body mb-0 p-0">


				                        <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
				                            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/5J-V4hAZt74" allowfullscreen></iframe>
				                        </div>

				                    </div>

				                    <!--Footer-->
				                    <div class="modal-footer justify-content-center">
				                        <span class="mr-4">Spread the word!</span>
				                        <a type="button" class="btn-floating btn-sm btn-fb"><i class="fa fa-facebook"></i></a>
				                        <!--Twitter-->
				                        <a type="button" class="btn-floating btn-sm btn-tw"><i class="fa fa-twitter"></i></a>
				                        <!--Google +-->
				                        <a type="button" class="btn-floating btn-sm btn-gplus"><i class="fa fa-google-plus"></i></a>
				                        <!--Linkedin-->
				                        <a type="button" class="btn-floating btn-sm btn-ins"><i class="fa fa-linkedin"></i></a>

				                        <button type="button" class="btn btn-outline-primary btn-rounded btn-md ml-4" data-dismiss="modal">Close</button>

				                    </div>

				                </div>
				                <!--/.Content-->

				            </div>
				        </div>
				        <!--Modal: Name-->

				        <a><img class="img-fluid z-depth-1" src="public/assets/img/video-screen2.png" alt="video" data-toggle="modal" data-target="#modal6"></a>

				    </div>
				    <!-- Grid column -->

				    <!-- Grid column -->
				    <div class="col-lg-4 col-md-6 mb-4">

				        <!--Modal: Name-->
				        <div class="modal fade" id="modal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				            <div class="modal-dialog modal-lg" role="document">

				                <!--Content-->
				                <div class="modal-content">

				                    <!--Body-->
				                    <div class="modal-body mb-0 p-0">
				                    	
				                        <div class="embed-responsive embed-responsive-16by9 z-depth-1-half">
				                            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/4tkfQHA4rX4" allowfullscreen></iframe>
				                        </div>

				                    </div>

				                    <!--Footer-->
				                    <div class="modal-footer justify-content-center">
				                        <span class="mr-4">Spread the word!</span>
				                        <a type="button" class="btn-floating btn-sm btn-fb"><i class="fa fa-facebook"></i></a>
				                        <!--Twitter-->
				                        <a type="button" class="btn-floating btn-sm btn-tw"><i class="fa fa-twitter"></i></a>
				                        <!--Google +-->
				                        <a type="button" class="btn-floating btn-sm btn-gplus"><i class="fa fa-google-plus"></i></a>
				                        <!--Linkedin-->
				                        <a type="button" class="btn-floating btn-sm btn-ins"><i class="fa fa-linkedin"></i></a>

				                        <button type="button" class="btn btn-outline-primary btn-rounded btn-md ml-4" data-dismiss="modal">Close</button>

				                    </div>

				                </div>
				                <!--/.Content-->

				            </div>
				        </div>
				        <!--Modal: Name-->

				        <a><img class="img-fluid z-depth-1" src="public/assets/img/video-screen3.png" alt="video" data-toggle="modal" data-target="#modal4"></a>

				    </div>
				    <!-- Grid column -->

				</div>
				<!-- Grid row -->
                
        
	</div>
</div>







