<div class="container-fluid" style="position: relative;">
	<div class="image" style="background-image: url('public/assets/css/img/background15.png');">
		<div class="image-background">
			<div class="content-gioithieu">
				<h2>GOGO</h2>
				<h5>Dịch vụ cho thuê xe tự lái hàng đầu Việt Nam</h5>
				<div class="separator line-separator">♦</div>
				<h5>Trang chủ/Tin Tức</h5>
			</div>
		</div>


	</div>
</div>
<div class="container-fluid">
	<div class="container" style="margin-bottom: 100px;">
		<div class="our-service">
			<h2>Một số tin tức nổi bật</h2>
			<div class="separator separator-danger">✻</div>
			<p>We promise you a new look and more importantly, a new attitude. We build that by getting to know you, your needs and creating the best looking clothes.</p>
		</div>
		<div class="row" style="margin-bottom: 200px">
			
                <div class="col-md-4">
                    <div class="box-blog imghvr-fade">
                    	<img src="public/assets/img/blog1.png" class="img-fluid">
                    	<figcaption>
                            <h4>Tên bài viết</h4>
                            <p>Tóm tắt</p>
                            <a href=""><i class="fa fa-search" aria-hidden="true"></i></a>
                        </figcaption>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="box-blog imghvr-fade">
                    	<img src="public/assets/img/blog2.png" class="img-fluid">
                    	<figcaption>
                            <h4>Tên bài viết</h4>
                            <p>Tóm tắt</p>
                            <a href=""><i class="fa fa-search" aria-hidden="true"></i></a>
                        </figcaption>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="box-blog imghvr-fade">
                    	<img src="public/assets/img/blog3.png" class="img-fluid">
                    	<figcaption >
                            <h4>Tên bài viết</h4>
                            <p>Tóm tắt</p>
                            <a href=""><i class="fa fa-search" aria-hidden="true"></i></a>
                        </figcaption>
                    </div>
                </div>
            
        </div>
        
        <div class="row">
        	<div class="col-md-8">
        		<h2 style="margin-bottom: 1.5rem!important;color: #000;font-size: 2rem;font-weight: 500;line-height: 1.2;font-family: "Josefin Sans", arial,sans-serif;">Tin tuc chinh</h2>
        		<div class="row">
		        	<div class="col-md-6">
		        		<div class="box-list-blog">
		        			<a href="">
		        			<img src="public/assets/img/blog3.png" class="img-fluid">
		        			<div class="blog-infor">
		        				<div class="post-title">
		        					<p><spam class="post-span">Car</spam><span class="post-span2">July 25,2018</span></p>
		        				</div>
		        				<h4>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h4>
		        			</div>
		        			</a>
		        		</div>
		        	</div>
		        	<div class="col-md-6">
		        		<div class="box-list-blog">
		        			<a href="">
		        			<img src="public/assets/img/blog3.png" class="img-fluid">
		        			<div class="blog-infor">
		        				<div class="post-title">
		        					<p><spam class="post-span">Car</spam><span class="post-span2">July 25,2018</span></p>
		        				</div>
		        				<h4>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h4>
		        			</div>
		        			</a>
		        		</div>
		        	</div>
		        	<div class="col-md-6">
		        		<div class="box-list-blog">
		        			<a href="">
		        			<img src="public/assets/img/blog3.png" class="img-fluid">
		        			<div class="blog-infor">
		        				<div class="post-title">
		        					<p><spam class="post-span">Car</spam><span class="post-span2">July 25,2018</span></p>
		        				</div>
		        				<h4>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h4>
		        			</div>
		        			</a>
		        		</div>
		        	</div>
		        	<div class="col-md-6">
		        		<div class="box-list-blog">
		        			<a href="">
		        			<img src="public/assets/img/blog3.png" class="img-fluid">
		        			<div class="blog-infor">
		        				<div class="post-title">
		        					<p><spam class="post-span">Car</spam><span class="post-span2">July 25,2018</span></p>
		        				</div>
		        				<h4>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h4>
		        			</div>
		        			</a>
		        		</div>
		        	</div>
	        	</div>
        	</div>

        	<div class="col-md-4">
        		<h2 style="margin-bottom: 1.5rem!important;color: #000;font-size: 2rem;font-weight: 500;line-height: 1.2;padding-left: 40px;">Người tìm xe</h2>
        		<div class="row" style="margin: auto;width: 85%">
        			<div class="col-md-12">
        				<div class="nguoi-tim-xe">
	        				<div class="avatar2 avatar-danger">
		                        <img alt="..." class="img-circle" src="public/assets/img/avatar1.jpg"/>
		                    </div>
		                    <div class="infor-tim-xe">
	                            <h4>Đặng Thái Sơn</h4>
	                            <h5>Giảng viên</h5>
	                            <p>Đừng so sánh mình với bất cứ ai trong thế giới này. Nếu bạn làm như vậy có nghĩa bạn đang sỉ nhục chính bản thân mình</p>
	                            <button type="button" class="read"><a href="">Read</a></button>
	                        </div>
	                	</div>
        			</div>
        		</div>

        	</div>
        </div>
	</div>
</div>

<div class="container-fluid">
	
		<div style="height: auto;background-color: #000;padding: 10px;">
			<div class="content-blog">
				<div class="container">
					<div class="row">
						<div class="col-md-4">
							<h2>Paragraph</h2>
							<img src="public/assets/img/blog4.png" class="img-fluid">
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi, accusantium optio unde perferendis eum illum voluptatibus dolore tempora, consequatur minus asperiores temporibus reprehenderit.</p>
						</div>
						
						<div class="col-md-1"></div>
						<div class="col-md-4">
							<h2>latest post</h2>
							<div class="row latest-post">
								<div class="col-md-4 col-4">
									<img src="public/assets/img/blog4.png" class="img-fluid">
								</div>
								<div class="col-md-8 col-8">
									<a href=""><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></a>
									<span>July 25,2018</span>

								</div>	

							</div>
							<div class="row latest-post">
								<div class="col-md-4 col-4">
									<img src="public/assets/img/blog4.png" class="img-fluid">
								</div>
								<div class="col-md-8 col-8">
									<a href=""><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></a>
									<span>July 25,2018</span>

								</div>	

							</div>
							<div class="row latest-post">
								<div class="col-md-4 col-4">
									<img src="public/assets/img/blog4.png" class="img-fluid">
								</div>
								<div class="col-md-8 col-8">
									<a href=""><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></a>
									<span>July 25,2018</span>

								</div>	

							</div>
						</div>
						<div class="col-md-3 popular-post">
							<h2>Most popular post</h2>
							<a href=""><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></a>
							<a href=""><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></a>
							<a href=""><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></a>
							<a href=""><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></a>

						</div>
					</div>
				</div>
			</div>
		</div>


	
</div>