<div class="container-fluid" style="position: relative;">
	<div class="image2" style="background-image: url('public/assets/css/img/background13.png');">
		<div class="image-background">
			<div class="content-register">
				<div class="box-register">
					<h2>Register</h2>
					<form method="post" enctype="multipart/form-data">
						<div class="row width">
							<input type="text" name="" placeholder="username">
						</div>
						<div class="row width">
							<input type="text" name="" placeholder="password">
						</div>
						<div class="row width">
							<input type="text" name="" placeholder="repassword">
						</div>
						<div class="row width">
							<input type="text" name="" placeholder="name">
						</div>
						<div class="row width">
							<input type="text" name="" placeholder="address">
						</div>
						<div class="row width">
							<input type="text" name="" placeholder="phone-number">
						</div>
						<div class="row width">
							<input type="text" name="" placeholder="email">
						</div>
						<div class="row width">
							<select id="soflow-color">
								<option>Gender</option>
								<option value="0">Man</option>
								<option value="1">Lady</option>
							</select>
						</div>
						<div class="row width">
							<input type="text" name="" placeholder="Job">
						</div>
						<div class="row width">
							<input type="file" name="" placeholder="">
						</div>
						

						<div class="row width">
							<input type="submit" name="" value="Register" class="register-submit">
						</div>

					</form>
				</div>	
					
			</div>
		</div>


	</div>
</div>